/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Actions: typeof import('./src/components/Actions.vue')['default']
    Build: typeof import('./src/components/Build.vue')['default']
    Compile: typeof import('./src/components/Compile.vue')['default']
    Debounce: typeof import('./src/components/Debounce.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    Features: typeof import('./src/components/Features.vue')['default']
    MiscConfig: typeof import('./src/components/MiscConfig.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Tapping: typeof import('./src/components/Tapping.vue')['default']
  }
}
